from parser import Parse

par = Parse()
result = par.parse("map.txt")
print(result.start)
print()
print(result.nb_drones)
print()
print(result.zones)
print()
print(result.end)
print()
print(result.Connections)
print()
print(result.get_neighbor("hub"))